name: cnnviz-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # or your preferred Python version
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - flask
  - memory_profiler
  - scikit-learn
  - streamlit
  - tensorflow
  - pydot
  - graphviz
  - pip
  - pip:
      # List pip-only packages here if needed


